name: btcpay_client
version: 0.1.1
description: Library to interact with a BTCPay or BitPay server. Usable in Flutter. Basic functionality is supported.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/btcpay_client

dependencies:
    pointycastle: ^1.0.0-rc4
    base58check: ^1.0.1
    convert: ^2.0.2
    asn1lib: ^0.5.1
    hex: ^0.1.2

dev_dependencies:
    test: ^1.3.4
    mock_web_server:
      git: https://gitlab.com/haarts/MockWebServer.git
      version: ^2.1.0
    args: ^1.5.0

environment:
    sdk: ">=2.0.0 <3.0.0"
