name: btcpay_client
version: 0.1.0
description: Library to interact with a BTCPay or BitPay server

dependencies:
    pointycastle: ^1.0.0-rc2
    base58check: ^1.0.1
    convert: ^2.0.2
    asn1lib: ^0.5.1

dev_dependencies:
    test: ^1.3.0

environment:
    sdk: "2.0.0"
