name: btcpay_client
version: 0.1.0
description: Library to interact with a BTCPay or BitPay server

dependencies:
    pointycastle: ^1.0.0-rc2
    test: ^1.3.0
    base58check: ^1.0.0
    convert: ^2.0.2
