name: btcpay_client
version: 0.1.3
description: Library to interact with a BTCPay or BitPay server. Usable in Flutter. Basic functionality is supported.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/btcpay_client

dependencies:
    pointycastle: ^1.0.2
    base58check: ^1.0.1
    convert: ^2.1.1
    asn1lib: ^0.6.0
    hex: ^0.1.2

dev_dependencies:
    test: ^1.11.1
    mock_web_server:
        git:
            url: git://github.com/haarts/MockWebServer.git
            ref: f8079e9f52ac45d920c677e545316a6905eaf819
    args: ^1.5.2
    pedantic: ^1.9.0

environment:
    sdk: ">=2.4.0 <3.0.0"
